import { Option } from "./components/select/select";
export const countryOptions: Option[] = [
  { country: "Albania", selected: false },
  { country: "Algeria", selected: false },
  { country: "Angola", selected: false },
  { country: "Argentina", selected: false },
  { country: "Armenia", selected: false },
  { country: "Australia", selected: false },
  { country: "Austria", selected: false },
  { country: "Azerbaijan", selected: false },
  { country: "Bahrain", selected: false },
  { country: "Bangladesh", selected: false },
  { country: "Belarus", selected: false },
  { country: "Belgium", selected: false },
  { country: "Benin", selected: false },
  { country: "Bolivia", selected: false },
  { country: "Bosnia and Herzegovina", selected: false },
  { country: "Botswana", selected: false },
  { country: "Brazil", selected: false },
  { country: "Brunei Darussalam", selected: false },
  { country: "Bulgaria", selected: false },
  { country: "Burkina Faso", selected: false },
  { country: "Cambodia", selected: false },
  { country: "Cameroon", selected: false },
  { country: "Canada", selected: false },
  { country: "Chad", selected: false },
  { country: "Chile", selected: false },
  { country: "China", selected: false },
  { country: "Chinese Taipei", selected: false },
  { country: "Colombia", selected: false },
  { country: "Congo", selected: false },
  { country: "Costa Rica", selected: false },
  { country: "Cote d'Ivoire", selected: false },
  { country: "Croatia", selected: false },
  { country: "Cuba", selected: false },
  { country: "Curacao", selected: false },
  { country: "Cyprus", selected: false },
  { country: "Czechia", selected: false },
  { country: "Denmark", selected: false },
  { country: "Dominican Republic", selected: false },
  { country: "DR Congo", selected: false },
  { country: "Ecuador", selected: false },
  { country: "Egypt", selected: false },
  { country: "El Salvador", selected: false },
  { country: "Equatorial Guinea", selected: false },
  { country: "Eritrea", selected: false },
  { country: "Estonia", selected: false },
  { country: "Ethiopia", selected: false },
  { country: "Finland", selected: false },
  { country: "France", selected: false },
  { country: "North Macedonia", selected: false },
  { country: "Gabon", selected: false },
  { country: "Georgia", selected: false },
  { country: "Germany", selected: false },
  { country: "Ghana", selected: false },
  { country: "Gibraltar", selected: false },
  { country: "Greece", selected: false },
  { country: "Guatemala", selected: false },
  { country: "Haiti", selected: false },
  { country: "Honduras", selected: false },
  { country: "Hong Kong", selected: false },
  { country: "Hungary", selected: false },
  { country: "Iceland", selected: false },
  { country: "India", selected: false },
  { country: "Indonesia", selected: false },
  { country: "Iran", selected: false },
  { country: "Iraq", selected: false },
  { country: "Ireland", selected: false },
  { country: "Israel", selected: false },
  { country: "Italy", selected: false },
  { country: "Jamaica", selected: false },
  { country: "Japan", selected: false },
  { country: "Jordan", selected: false },
  { country: "Kazakhstan", selected: false },
  { country: "Kenya", selected: false },
  { country: "Korea", selected: false },
  { country: "Korea, DPR", selected: false },
  { country: "Kosovo", selected: false },
  { country: "Kuwait", selected: false },
  { country: "Kyrgyzstan", selected: false },
  { country: "Lao PDR", selected: false },
  { country: "Latvia", selected: false },
  { country: "Lebanon", selected: false },
  { country: "Libya", selected: false },
  { country: "Lithuania", selected: false },
  { country: "Luxembourg", selected: false },
  { country: "Madagascar", selected: false },
  { country: "Malaysia", selected: false },
  { country: "Mali", selected: false },
  { country: "Malta", selected: false },
  { country: "Mauritania", selected: false },
  { country: "Mauritius", selected: false },
  { country: "Mexico", selected: false },
  { country: "Moldova", selected: false },
  { country: "Mongolia", selected: false },
  { country: "Montenegro", selected: false },
  { country: "Morocco", selected: false },
  { country: "Mozambique", selected: false },
  { country: "Myanmar", selected: false },
  { country: "Namibia", selected: false },
  { country: "Nepal", selected: false },
  { country: "Netherlands", selected: false },
  { country: "New Zealand", selected: false },
  { country: "Nicaragua", selected: false },
  { country: "Niger", selected: false },
  { country: "Nigeria", selected: false },
  { country: "Norway", selected: false },
  { country: "Oman", selected: false },
  { country: "Pakistan", selected: false },
  { country: "Panama", selected: false },
  { country: "Paraguay", selected: false },
  { country: "Peru", selected: false },
  { country: "Philippines", selected: false },
  { country: "Poland", selected: false },
  { country: "Portugal", selected: false },
  { country: "Qatar", selected: false },
  { country: "Romania", selected: false },
  { country: "Russia", selected: false },
  { country: "Rwanda", selected: false },
  { country: "Saudi Arabia", selected: false },
  { country: "Senegal", selected: false },
  { country: "Serbia", selected: false },
  { country: "Singapore", selected: false },
  { country: "Slovak Republic", selected: false },
  { country: "Slovenia", selected: false },
  { country: "South Africa", selected: false },
  { country: "South Sudan", selected: false },
  { country: "Spain", selected: false },
  { country: "Sri Lanka", selected: false },
  { country: "Sudan", selected: false },
  { country: "Suriname", selected: false },
  { country: "Eswatini", selected: false },
  { country: "Sweden", selected: false },
  { country: "Switzerland", selected: false },
  { country: "Syria", selected: false },
  { country: "Tajikistan", selected: false },
  { country: "Tanzania", selected: false },
  { country: "Thailand", selected: false },
  { country: "Togo", selected: false },
  { country: "Trinidad and Tobago", selected: false },
  { country: "Tunisia", selected: false },
  { country: "Turkiye", selected: false },
  { country: "Turkmenistan", selected: false },
  { country: "Uganda", selected: false },
  { country: "Ukraine", selected: false },
  { country: "United Arab Emirates", selected: false },
  { country: "United Kingdom", selected: false },
  { country: "United States", selected: false },
  { country: "Uruguay", selected: false },
  { country: "Uzbekistan", selected: false },
  { country: "Venezuela", selected: false },
  { country: "Viet Nam", selected: false },
  { country: "Yemen", selected: false },
  { country: "Zambia", selected: false },
  { country: "Zimbabwe", selected: false },
];
